// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boqmpnebjjzrhjgnrrsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcW1wbmViamp6cmhqZ25ycnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzU0MTEsImV4cCI6MjA1OTQ1MTQxMX0.mPEer2is5TqkDDL4P1qyRZjL6v6yjj6m8ABOvmGioGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);